language: python
script:
  - CHANGED_FILES=($(git diff --name-only $TRAVIS_COMMIT_RANGE | grep -E ".+\/.+\.md")) || true;
  - echo $CHANGED_FILES
  - python scripts/collectalk.py validate --file $CHANGED_FILES
